#! /bin/bash
#
# juppline 1.1.0
#
# Opens the text editor jupp at the first line of a file containing a user given string.
#

function hilfe {
 echo " 
 AUFRUF:
 juppline zu_findender_Text Dateiname
"
}

function en_help {
 echo " 
 CALL:
 juppline string_to_find file_name
"
}

case "$1" in
  --hilf)
    hilfe
    exit 0
    ;;
  --help|-h)
    if [ "${LANG:0:2}" != 'de' ]; then
      en_help
    else
      hilfe
    fi
    exit 0
    ;;
esac

searched="$(grep -n -m1 "$1" "$2")"
if [ -n "$searched" ]; then
  jupp +"${searched%%:*}" "$2"
else
  jupp "$2"
fi

exit 0
